13
/data/ljo31/Lens/J0901/gui_emcee10a
Source 2
Source 1
28 28
60
1
60
2
60
3
60
4
           xoffset     0.778
           yoffset     1.455
        Galaxy 1 x    44.701
        Galaxy 1 y    37.789
        Galaxy 1 q     0.798
       Galaxy 1 pa   -16.356
       Galaxy 1 re    17.926
        Galaxy 1 n     3.972
          Lens 1 x    45.328
          Lens 1 y    37.191
          Lens 1 q     0.804
         Lens 1 pa    20.237
          Lens 1 b    13.296
        Lens 1 eta     1.015
          extShear     0.057
       extShear PA   102.988
        Source 2 q     0.994
       Source 2 re    16.006
        Source 2 n     3.559
       Source 2 pa    23.538
        Source 2 x    -5.136
        Source 2 y    -1.444
        Source 1 q     0.586
       Source 1 re     7.601
        Source 1 n     3.814
       Source 1 pa    33.769
        Source 1 x    -4.720
        Source 1 y    -2.132
13
/data/ljo31/Lens/J0901/gui_emcee10a
Source 2
Source 1
28 28
0
60
1
60
2
60
3
60
4
           xoffset     1.162
           yoffset     0.927
        Galaxy 1 x    45.116
        Galaxy 1 y    38.050
        Galaxy 1 q     0.668
       Galaxy 1 pa   -11.674
       Galaxy 1 re    19.002
        Galaxy 1 n     3.410
          Lens 1 x    45.196
          Lens 1 y    37.244
          Lens 1 q     0.881
         Lens 1 pa    16.933
          Lens 1 b    13.493
        Lens 1 eta     1.070
          extShear     0.017
       extShear PA   -65.155
        Source 2 q     0.323
       Source 2 re    25.763
        Source 2 n     3.446
       Source 2 pa    26.671
        Source 2 x    -5.052
        Source 2 y    -1.362
        Source 1 q     0.773
       Source 1 re     5.245
        Source 1 n     3.623
       Source 1 pa   -19.518
        Source 1 x    -4.830
        Source 1 y    -1.959
1
0
2
3
1
4
2
5
6
3
7
8
4
9
Traceback (most recent call last):
  File "LindzFit_J0901_grr.py", line 434, in <module>
    models.append(model)
  File "LindzFit_J0901_grr.py", line 42, in NotPlicely
    pl.figure()
  File "/opt/ioa/software/python/2.7.8/lib/python2.7/site-packages/matplotlib/pyplot.py", line 423, in figure
    **kwargs)
  File "/opt/ioa/software/python/2.7.8/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 79, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/opt/ioa/software/python/2.7.8/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 87, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/opt/ioa/software/python/2.7.8/lib/python2.7/lib-tk/Tkinter.py", line 1764, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:102.0"
5
6
7
8
9
Traceback (most recent call last):
  File "LindzFit_J0901_grr.py", line 434, in <module>
    models.append(model)
  File "LindzFit_J0901_grr.py", line 42, in NotPlicely
    pl.figure()
  File "/opt/ioa/software/python/2.7.8/lib/python2.7/site-packages/matplotlib/pyplot.py", line 423, in figure
    **kwargs)
  File "/opt/ioa/software/python/2.7.8/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 79, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/opt/ioa/software/python/2.7.8/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 87, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/opt/ioa/software/python/2.7.8/lib/python2.7/lib-tk/Tkinter.py", line 1764, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
